import { Transaction, BudgetConfig } from "../types";

export const DEFAULT_BUDGET_CONFIG: BudgetConfig = {
  monthlyBudget: 3800,
  currency: "$",
  categoryBudgets: {
    Rent: 1650,
    Groceries: 550,
    Travel: 400,
    Shopping: 300,
    Subscriptions: 90,
    "Food & Dining": 350,
    Utilities: 220,
    Transportation: 180,
    Entertainment: 120,
  },
};

// Generate realistic date strings relative to current date (Aug 2026)
export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-01",
    title: "Monthly Apartment Rent Payment",
    location: "Highland Residences (Portal)",
    amount: 1650.0,
    category: "Rent",
    type: "expense",
    date: "2026-08-01",
    paymentMethod: "Bank Transfer / UPI",
    notes: "August apartment rent & trash fee",
    recurring: true,
    createdAt: "2026-08-01T09:00:00Z",
  },
  {
    id: "tx-02",
    title: "Roundtrip Flight to Seattle",
    location: "Delta Air Lines - JFK to SEA",
    amount: 348.6,
    category: "Travel",
    type: "expense",
    date: "2026-08-03",
    paymentMethod: "Credit Card",
    notes: "Summer weekend trip flight booking",
    createdAt: "2026-08-03T14:22:00Z",
  },
  {
    id: "tx-03",
    title: "Weekly Organic Food Haul",
    location: "Trader Joe's - 14th St",
    amount: 86.45,
    category: "Groceries",
    type: "expense",
    date: "2026-08-04",
    paymentMethod: "Credit Card",
    notes: "Produce, sourdough bread, organic chicken, almond milk",
    createdAt: "2026-08-04T17:15:00Z",
  },
  {
    id: "tx-04",
    title: "Netflix 4K Ultra HD Plan",
    location: "Netflix.com",
    amount: 22.99,
    category: "Subscriptions",
    type: "expense",
    date: "2026-08-05",
    paymentMethod: "Credit Card",
    notes: "Monthly recurring streaming family subscription",
    recurring: true,
    createdAt: "2026-08-05T02:10:00Z",
  },
  {
    id: "tx-05",
    title: "Spotify Duo Music Plan",
    location: "Spotify",
    amount: 14.99,
    category: "Subscriptions",
    type: "expense",
    date: "2026-08-05",
    paymentMethod: "Credit Card",
    notes: "Ad-free music and podcasts",
    recurring: true,
    createdAt: "2026-08-05T03:00:00Z",
  },
  {
    id: "tx-06",
    title: "Summer Wardrobe & Running Shoes",
    location: "Nike Store & Zara",
    amount: 142.5,
    category: "Shopping",
    type: "expense",
    date: "2026-08-07",
    paymentMethod: "Digital Wallet (Apple/Google Pay)",
    notes: "Pegasus running shoes + 2 linen shirts",
    createdAt: "2026-08-07T16:40:00Z",
  },
  {
    id: "tx-07",
    title: "Home Internet Fiber 1Gbps",
    location: "Verizon Fios",
    amount: 79.99,
    category: "Utilities",
    type: "expense",
    date: "2026-08-08",
    paymentMethod: "Credit Card",
    notes: "High speed internet monthly bill",
    recurring: true,
    createdAt: "2026-08-08T08:30:00Z",
  },
  {
    id: "tx-08",
    title: "Electric & Power Bill",
    location: "ConEdison Power Grid",
    amount: 114.3,
    category: "Utilities",
    type: "expense",
    date: "2026-08-10",
    paymentMethod: "Bank Transfer / UPI",
    notes: "AC cooling electric bill for late July",
    createdAt: "2026-08-10T11:00:00Z",
  },
  {
    id: "tx-09",
    title: "Bulk Household & Pantry Supplies",
    location: "Costco Wholesale - Queens",
    amount: 194.2,
    category: "Groceries",
    type: "expense",
    date: "2026-08-11",
    paymentMethod: "Debit Card",
    notes: "Olive oil, paper towels, detergent, sparkling water",
    createdAt: "2026-08-11T13:45:00Z",
  },
  {
    id: "tx-10",
    title: "Living Room Floor Lamp & Cushion",
    location: "IKEA Brooklyn",
    amount: 118.0,
    category: "Housing",
    type: "expense",
    date: "2026-08-13",
    paymentMethod: "Credit Card",
    notes: "Living room setup decor and warm lighting",
    createdAt: "2026-08-13T15:20:00Z",
  },
  {
    id: "tx-11",
    title: "Weekend Dinner & Drinks with Friends",
    location: "Osteria Morini Italian Restaurant",
    amount: 88.5,
    category: "Food & Dining",
    type: "expense",
    date: "2026-08-14",
    paymentMethod: "Credit Card",
    notes: "Handmade pasta, burrata and glass of pinot noir",
    createdAt: "2026-08-14T20:30:00Z",
  },
  {
    id: "tx-12",
    title: "Seattle Mountain View Loft Stay",
    location: "Airbnb - Downtown Seattle",
    amount: 215.0,
    category: "Travel",
    type: "expense",
    date: "2026-08-16",
    paymentMethod: "Credit Card",
    notes: "2 nights weekend accommodation",
    createdAt: "2026-08-16T12:00:00Z",
  },
  {
    id: "tx-13",
    title: "Mid-month Fresh Grocery Restock",
    location: "Whole Foods Market - Union Sq",
    amount: 72.8,
    category: "Groceries",
    type: "expense",
    date: "2026-08-18",
    paymentMethod: "Digital Wallet (Apple/Google Pay)",
    notes: "Organic blueberries, Greek yogurt, salmon filets",
    createdAt: "2026-08-18T18:10:00Z",
  },
  {
    id: "tx-14",
    title: "ChatGPT Plus & GitHub Copilot",
    location: "OpenAI & GitHub",
    amount: 30.0,
    category: "Subscriptions",
    type: "expense",
    date: "2026-08-20",
    paymentMethod: "Credit Card",
    notes: "AI coding and research tools",
    recurring: true,
    createdAt: "2026-08-20T10:00:00Z",
  },
  {
    id: "tx-15",
    title: "Ergonomic Desk Accessories & Cables",
    location: "Amazon.com",
    amount: 64.9,
    category: "Shopping",
    type: "expense",
    date: "2026-08-22",
    paymentMethod: "Credit Card",
    notes: "USB-C monitor hub & laptop riser",
    createdAt: "2026-08-22T11:25:00Z",
  },
  {
    id: "tx-16",
    title: "Fuel Fill Up (Full Tank)",
    location: "Shell Gas Station - Grand Central Pkwy",
    amount: 48.75,
    category: "Transportation",
    type: "expense",
    date: "2026-08-24",
    paymentMethod: "Credit Card",
    notes: "12.5 gallons regular unleaded",
    createdAt: "2026-08-24T08:15:00Z",
  },
  {
    id: "tx-17",
    title: "Specialty Espresso Beans & Bakery",
    location: "Blue Bottle Coffee",
    amount: 24.5,
    category: "Food & Dining",
    type: "expense",
    date: "2026-08-25",
    paymentMethod: "Digital Wallet (Apple/Google Pay)",
    notes: "Bella Donovan whole beans & almond croissant",
    createdAt: "2026-08-25T09:40:00Z",
  },
  {
    id: "tx-18",
    title: "Farmers Market Fresh Vegetables",
    location: "Greenmarket Farmers Market",
    amount: 38.2,
    category: "Groceries",
    type: "expense",
    date: "2026-08-27",
    paymentMethod: "Cash",
    notes: "Heirloom tomatoes, fresh basil, peaches and honey",
    createdAt: "2026-08-27T11:00:00Z",
  },
  {
    id: "tx-income-01",
    title: "Bi-Weekly Tech Salary Deposit",
    location: "TechCorp Global Payroll",
    amount: 2950.0,
    category: "Salary / Income",
    type: "income",
    date: "2026-08-01",
    paymentMethod: "Bank Transfer / UPI",
    notes: "First half monthly net salary",
    createdAt: "2026-08-01T06:00:00Z",
  },
  {
    id: "tx-income-02",
    title: "Bi-Weekly Tech Salary Deposit",
    location: "TechCorp Global Payroll",
    amount: 2950.0,
    category: "Salary / Income",
    type: "income",
    date: "2026-08-15",
    paymentMethod: "Bank Transfer / UPI",
    notes: "Second half monthly net salary",
    createdAt: "2026-08-15T06:00:00Z",
  },
];
